service: notes-serverless-api

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-2

  environment:
    tableName: notes

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: 'arn:aws:dynamodb:us-east-2:*:*'

functions:
  create:
    handler: src/create.main
    events:
      - http:
          path: notes
          method: post
          authorizer: aws_iam
  get:
    handler: src/get.main
    events:
      - http:
          path: notes/{id}
          method: get
          authorizer: aws_iam
  list:
    handler: src/list.main
    events:
      - http:
          path: notes
          method: get
          authorizer: aws_iam
  update:
    handler: src/update.main
    events:
      - http:
          path: notes/{id}
          method: put
          authorizer: aws_iam
  delete:
    handler: src/delete.main
    events:
      - http:
          path: notes/{id}
          method: delete
          authorizer: aws_iam
